version: '2'
services:
  app:
    build: ./app
    command: bundle exec rails s -p 3000 -b '0.0.0.0' -e development
    volumes:
      - ./app:/usr/src/app
    links:
      - db
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    env_file:
      - ./commons.env
      - ./secrets.env
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: superacao
      POSTGRES_USER: superacao
      POSTGRES_PASSWORD: 123456
